policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      dco: false
      gpg: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - "chore"
          - "docs"
          - "style"
          - "build"
        scopes:
          - "provider"
          - "sdk"
          - "ci"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        This is the contents of a license header.
