version: 1
updates_configs:
  - package_manager: "go:modules"
    directory: "/(provider|sdk)"
    update_schedule: "daily"
    default_reviewers:
      - jaxxstorm
    default_labels:
      - dependencies
      - dependabot

