version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/sdk"
    update_schedule: "daily"
    default_reviewers:
      - jaxxstorm
    default_labels:
      - dependencies
      - dependabot
  - package_manager: "go:modules"
    directory: "/provider"
    update_schedule: "daily"
    default_reviewers:
      - jaxxstorm
    default_labels:
      - dependencies
      - dependabot

